[package]
name = "font-kit"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
description = "A cross-platform font loading library"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/pcwalton/font-kit"
homepage = "https://github.com/pcwalton/font-kit"

[features]
loader-freetype = ["freetype"]
loader-freetype-default = ["loader-freetype"]
source-fontconfig = ["servo-fontconfig"]
source-fontconfig-default = ["source-fontconfig"]

[dependencies]
bitflags = "1.0"
byteorder = "1.2"
dirs = "1.0"
euclid = "0.19"
failure = "0.1"
float-ord = "0.2"
itertools = "0.7"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
lyon_path = "0.12"
memmap = "0.6"
walkdir = "2.1"

[dependencies.freetype]
version = "^0.4.1"
optional = true

[dependencies.servo-fontconfig]
version = "0.4"
optional = true

[dev-dependencies]
clap = "2.32"
colored = "1.6"
pbr = "1.0"
prettytable-rs = "0.7"

[target.'cfg(target_family = "windows")'.dependencies]
dwrote = "0.5"

[target.'cfg(target_family = "windows")'.dependencies.winapi]
version = "0.3"
features = ["minwindef", "winbase"]

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.18"
core-foundation = "0.6"
core-graphics = "^0.17.1"
core-text = "13.0"

[target.'cfg(not(any(target_family = "windows", target_os = "macos")))'.dependencies]
freetype = "^0.4.1"
servo-fontconfig = "0.4"
